package net.lacnic.epp.util;

public enum TipoXML {
	LOGIN,
	LOGIN_EXT_URI,
	LOGOUT,
	GENERIC_ADDRESS,
	GENERIC_PHONE,
	
	CONTACT_CREATE,
	CONTACT_UPDATE,
	CONTACT_INFO,
	CONTACT_AUTH_INFO,
	
	ORG_UPDATE_CONTACT, //edita un solo contacto
	ORG_UPDATE_CONTACTS, // edita varios a la vez
	ORG_CONTACT,
	ORG_CREATE,
	ORG_UPDATE,
	ORG_CREATE_EPP_IP,
	ORG_CREATE_RENEWALL_TYPE,
	
	IPNETWORK_REVERSES_DNS,
	IPNETWORK_DSDATA_DNS,
	IPNETWORK_REVERSES_DNS_HOSTNAME, 
	IPNETWORK_RANGE,
	IPNETWORK_CONTACT,
	IPNETWORK_UPDATE_CONTACTS,
	IPNETWORK_CREATE,
	IPNETWORK_UPDATE, //UTILIZADO SOLO PARA EDITAR REVERSOS
	IPNETWORK_UPDATE_ASN, //PARA EDITAR EL ASN ANNOUNCER DEL BLOQUE
	IPNETWORK_DELETE,
	IPNETWORK_INFO, 
	
	ASN_INFO,
	ASN_UPDATE,
	ASN_CONTACT,
	ASN_UPDATE_CONTACTS,
	
	HELLO;
}